### ISSUE TITLE
Render to image?

### ISSUE THREAD

**Issue by hopewise** [kevinkhill/lavacharts#125]
Hello,

I just discovered this repo! I am wondering if it has the capability to render to image? instead of JavaScript based charts?

**Comment by kevinkhill** [comment]
I'm working on it ;)
I have it working in the 3.1 branch, but there's no docs yet. I will be porting it back into 3.0 since it's a popular request

**Comment by hopewise** [comment]
Great! So any expected date? This would be really handy, specially for
stacked bar charts.. :)

**Comment by kevinkhill** [comment]
I can't make any promises because I am slammed with work at my day job. But, hopefully soon.

**Comment by hopewise** [comment]
Good luck, and thanks for great work :)

**Comment by kevinkhill** [comment]
I am working on backporting some of the 3.1 features I have ready into the 3.0 branch. I was thinking about it and I would rather not separate users into groups of 2.5, 3.0, and 3.1

**Comment by kevinkhill** [comment]
I have working PNG charts if you want to try out the ```dev-3.0``` dependency over ```3.0.*``` Once I have finished testing and documentation, then a new tag will be released and you can continue to use the ```3.0.*```

Just add to your chart's options, ```[ 'png' => true ]``` and it should come out as a static image

**Comment by hopewise** [comment]
Thanks I will test when I have time, but in general, how do you convert to
image? As you need to run the javascript code at the server side??

On Tue, Apr 26, 2016 at 5:44 PM, Kevin Hill <notifications@github.com>
wrote:

> I have working PNG charts if you want to try out the dev-3.0 dependency
> over 3.0.* Once I have finished testing and documentation, then a new tag
> will be released and you can continue to use the 3.0.*
>
> Just add to your chart's options, [ 'png' => true ] and it should come
> out as a static image
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinkhill/lavacharts/issues/125#issuecomment-214768812>
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by kevinkhill** [comment]
I don't generate the image at all. Google offers a method of the chart, to get a text encoded png. My option just has the chart render in page, the swapped out for the static version.

**Comment by hopewise** [comment]
Ah,ok, do you know of a possible way to generate a powerpoint doc of
generated chart images?

On Fri, Apr 29, 2016 at 6:03 AM, Kevin Hill <notifications@github.com>
wrote:

> I don't generate the image at all. Google offers a method of the chart, to
> get a text encoded png. My option just has the chart render in page, the
> swapped out for the static version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinkhill/lavacharts/issues/125#issuecomment-215616496>
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by kevinkhill** [comment]
A quick google brought me to [PHPOffice/PHPPresentation](https://github.com/PHPOffice/PHPPresentation), but I have never used it before

**Comment by hopewise** [comment]
wow! thnx  :)

On Fri, Apr 29, 2016 at 7:13 PM, Kevin Hill <notifications@github.com>
wrote:

> A quick google brought me to PHPOffice/PHPPresentation
> <https://github.com/PHPOffice/PHPPresentation>, but I have never used it
> before
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinkhill/lavacharts/issues/125#issuecomment-215785591>
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by Alviero** [comment]
Hi, I'm trying to use your lavacharts in a project of mine.
I need to create a pdf file (I'm using fpdf inside laravel 5.2).
Since I need to put a chart as image in the pdf generated with mysql data I would understand if it possible to render as image and put it directly in the pdf with the $pdf->Image method of fpdf.
I cannot use javascript because I have the code in a controller that must create and serve the pdf to the user.
I read in this page "Just add to your chart's options, [ 'png' => true ] and it should come out as a static image", can you tell me if is what I'm seeking?
Thanks in advance!!!

**Comment by kevinkhill** [comment]
My "static image" implementation of the chart, is actually just a swap of the svg for the png, *in page*. I can't actually make it be static, in memory, since Javascript has to be executed to get the chart. (The Google Chart API is Javascript)

The only way I can think for this to work would be using phantomjs to render the chart in memory, taking a "screen shot" of the chart, saving it out and then using it in your controller. 

Convoluted? Yes. But I don't know any other way to remove the step where a page has to be rendered for the javascript to execute. This is Google's limitation and I can't change that.

**Comment by kevinkhill** [comment]
Closing due to being out of the scope of the project
