### ISSUE TITLE
Lava is not found

### ISSUE THREAD

**Issue by ianvani** [kevinkhill/lavacharts#137]
Hi, i am using laravel 5.2 and khill/lavacharts ^3.0. Let me know lavacharts is supported with laravel 5.2 version? I tried all these answers for existing issue "Lava not found" but i cant fix this issue.

**Comment by kevinkhill** [comment]
It is definitely supported. I have had other users report this same issue but I never have encountered this bug in development so I'm not sure how to help.

Try going through the install process again? Delete the Khill folder from vendor, remove from composer. Remove the service provider line from your config and try installing again.

**Comment by poerkiemen** [comment]
Hey, I was trying to get it working too and I encountered the same issue.
I'm using laravel 5.2.31 and the latest stable version of Lavacharts 3.0.4.
I've tried reïnstalling it the way you described but that didn't solve it either.

**Comment by poerkiemen** [comment]
A quick update:
using:
use Khill\Lavacharts\Laravel\LavachartsFacade as Lava;
does fix the issue. (read that in a similar issue related to laravel 5.1.*)
ideally you want "use Khill\Lavacharts\Lavacharts;" to be enough ofcourse!

**Comment by ianvani** [comment]
Hi, i reinstalled both  khill/lavacharts and khill/datatableplus. Also, i used 
use Khill\Lavacharts\Laravel\LavachartsFacade as Lava;
Now it works fine.

**Comment by kevinkhill** [comment]
@poerkiemen I would recommend against creating an instance manually unless you plan on keeping track of it or passing it to the views for rendering. Or getting the js in the controller and passing it to the view. The whole idea of the service provider was to keep the one instance shared through the app. I will dig deeper since you guys keep having issues.

**Comment by kevinkhill** [comment]
I will leave off moving the Alias from automatic assignment to manual for 3.1 since that would break many apps that rely on the automatic assignment of the alias. I will have to do more tests against fresh installs of L5.2, but right now I am busy with my life and don't have much time to work on this.

**Comment by kevinkhill** [comment]
Automatic alias assignment will stay in the ServiceProvider, as long as Laravel supports it. I like the feature and I'm sure others find it useful as one less step to take care of. Closing this issue for now.
