### ISSUE TITLE
Lavacharts events not working

### ISSUE THREAD

**Issue by kdyadav3012** [kevinkhill/lavacharts#152]

**Comment by kdyadav3012** [comment]
Have same issue as in this post http://stackoverflow.com/questions/36844949/lavacharts-ready-event-not-being-fired

**Comment by kevinkhill** [comment]
I tried to comment on SO but I have no rep, so they deleted my "answer"

What I said was:
So I'm not even sure where I left off in development, because my full time job and home life have left me with no time for working on the package. I believe I left working code, where I reworked much of the lava.js module in a branch on Github. You can try checking out one of the branches or, using lava.getChart() and manually assigning the event.

**Comment by kevinkhill** [comment]
The master branch, which will soon become 3.1 should have support for events. Please re-open or start a new issue if needed.
