### ISSUE TITLE
Bug with dev-master using Laravel 5.2

### ISSUE THREAD

**Issue by schonhose** [kevinkhill/lavacharts#157]
Not sure if you are aware of this, but there is an error in the dev version of Lavacharts. I wanted to test this because the new option for png images sounds promising for getting images easier in PDF files.

The error is:
> FatalErrorException in Chart.php line 29: Access level to Khill\Lavacharts\Support\Traits\RenderableTrait::generateElementId() must be public (as in class Khill\Lavacharts\Support\Contracts\RenderableInterface)

For now I will switch back to the stable 3.0.x version.

**Comment by TheTechnoMan** [comment]
Hey,

I'm getting a similar error:

> local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Access level to Khill\Lavacharts\Support\Traits\RenderableTrait::generateElementId() must be public (as in class Khill\Lavacharts\Support\Contracts\RenderableInterface)' in C:\Users\Michael\Documents\Projects\Laravel\X\vendor\khill\lavacharts\src\Charts\Chart.php:196

It is however weird that I'm using Laravel 5.1 and the same version works fine on my other system, but does not on this one, even though I'm using the same code and composer file. Any idea what could cause this problem?

Switching back to ~3.0 does not work either because it looks like that the AJAX feature is not available or at least different from the dev version.

Thanks a lot!

**Comment by TheTechnoMan** [comment]
Well, the generateElementId() function inside RenderableTrait.php file is marked as private instead of public. When I change it to public, it works just fine. Could you please change that in the dev branch?

Thanks

**Comment by kevinkhill** [comment]
Could you whip up a pull request? I can click merge much easier that getting into my laptop to push edits :smile:

**Comment by kevinkhill** [comment]
I popped in real quick to switch that to public, so the master branch should be ok now..... *should*....
