### ISSUE TITLE
Unable to render Areachart. Cannot read property 'x' of null

### ISSUE THREAD

**Issue by kyranb** [kevinkhill/lavacharts#223]
#### What Version?
> Run `composer show khill/lavacharts` if you don't know

3.1.8 (latest as of now)

#### Issue
Areachart is showing the error: `Cannot read property 'x' of null`

![screenshot 2017-09-20 22 32 33](https://user-images.githubusercontent.com/5426926/30644985-9d074532-9e57-11e7-8e6e-3bb22c2d1b43.png)

This is the rendered JS code:

```js

/* jshint undef: true, unused: true */
/* globals lava, google */

(function(){
    "use strict";

    var $chart = lava.createChart('AreaChart', 'chartName');

    $chart.init = function() {
        $chart.package = 'corechart';
        $chart.setElement('chartName-div');
        $chart.setPngOutput();

        $chart.configure = function () {
            $chart.render = function (data) {
                $chart.setData({"cols":[{"type":"date","label":"Date"},{"type":"number","label":"Downloads"},{"type":"string","p":{"role":"annotation"}}],"rows":[{"c":[{"v":new Date(2017,8,20,15,46,30)},{"v":196},{"v":"Ep. 90 (The Spider...)"}]},{"c":[{"v":new Date(2017,8,19,15,46,30)},{"v":121},{"v":null}]},{"c":[{"v":new Date(2017,8,18,15,46,30)},{"v":138},{"v":null}]},{"c":[{"v":new Date(2017,8,17,15,46,30)},{"v":269},{"v":"Ep. 89 (Eating Edi...)"}]},{"c":[{"v":new Date(2017,8,16,15,46,30)},{"v":95},{"v":null}]},{"c":[{"v":new Date(2017,8,15,15,46,30)},{"v":225},{"v":null}]},{"c":[{"v":new Date(2017,8,14,15,46,30)},{"v":219},{"v":null}]},{"c":[{"v":new Date(2017,8,13,15,46,30)},{"v":110},{"v":null}]},{"c":[{"v":new Date(2017,8,12,15,46,30)},{"v":168},{"v":null}]},{"c":[{"v":new Date(2017,8,11,15,46,30)},{"v":266},{"v":"Ep. 88 (Your Going...)"}]},{"c":[{"v":new Date(2017,8,10,15,46,30)},{"v":27},{"v":null}]},{"c":[{"v":new Date(2017,8,9,15,46,30)},{"v":53},{"v":null}]},{"c":[{"v":new Date(2017,8,8,15,46,30)},{"v":62},{"v":null}]},{"c":[{"v":new Date(2017,8,7,15,46,30)},{"v":120},{"v":null}]},{"c":[{"v":new Date(2017,8,6,15,46,30)},{"v":137},{"v":null}]}]});

                $chart.options = {"animation":{"startup":true,"duration":1000,"easing":"linear"},"legend":{"position":"none"},"vAxis":{"format":"short","minValue":4},"fontName":"Helvetica Neue","chartArea":{"width":"90%","height":"85%"},"colors":["#b0b3e3"]};

                $chart.chart = new google.visualization.AreaChart($chart.element);

                
           

                $chart.chart.draw($chart.data, $chart.options);

                if ($chart.pngOutput === true) {
                    $chart.drawPng();
                }

                $chart.promises.rendered.resolve();
                return $chart.promises.rendered.promise;
            };

            $chart.promises.configure.resolve();
            return $chart.promises.configure.promise;
        };

        lava.emit('ready', $chart);
    };

    lava.store($chart);
})();

```

#### Controller Code (chart creation code)

```php

$lava = new Lavacharts();
$chartname = $lava->DataTable();
$chartname->addDateColumn('Date')->setDateTimeFormat('Y-m-d')->setTimezone('usersTimezone')
->addNumberColumn('count')
->addRoleColumn('string', 'annotation');

// add values to $chartname

$areachart = Lava::AreaChart('chartname', $chartname, [
             'animation' => ['startup' => true, 'duration' => 1000, 'easing' => 'linear'],
             'legend' => ['position' => 'none'],
             'vAxis' => ['format' => 'short', 'minValue' => 4],
             'fontName' => 'Helvetica Neue',
             'chartArea' => ['width' => '90%', 'height' => '85%'],
             'colors' => ['#b0b3e3'],
         ]);

return $areachart->getDataTableJson();


```

#### View Code
```
@areachart('chartname', 'chartname-div')
```

**Comment by kevinkhill** [comment]
Here is a few things I notice off the bat:

The line `$lava = new Lavacharts();` is not needed, since the service provider is already holding the instance of the library for you (could lead to confusion). You can use the `Lava::` alias to create your DataTable with `$chartname = Lava::DataTable();`

That's not that important, but continuing...

Assigning the `Lava::AreaChart` to `$areachart` isn't needed, unless you are loading the chart data via ajax. (Is that why you are `return $areachart->getDataTableJson();` because if not, you don't have to return anything.)

Just defining the chart with `Lava::AreaChart('chartname', $chartname, [......` is all you need to use it in the view.

[I used your Controller code](https://github.com/lavacharts/issues/blob/master/223_cant-read-property-x-of-null/index.php), with a couple data points to test, and it rendered fine for me.

![image](https://user-images.githubusercontent.com/266076/30676703-46a63682-9e3c-11e7-9e6b-e15c8cb57749.png)

Can you post what `// add values to $chartname` is? or are you actually not adding any data initially, with the intent of loading after the fact?

**Comment by kevinkhill** [comment]
Here is a few things I notice off the bat:

The line `$lava = new Lavacharts();` is not needed, since the service provider is already holding the instance of the library for you (could lead to confusion). You can use the `Lava::` alias to create your DataTable with `$chartname = Lava::DataTable();`

That's not that important, but continuing...

Assigning the `Lava::AreaChart` to `$areachart` isn't needed, unless you are loading the chart data via ajax. (Is that why you are `return $areachart->getDataTableJson();` because if not, you don't have to return anything.)

Just defining the chart with `Lava::AreaChart('chartname', $chartname, [......` is all you need to use it in the view.

[I used your Controller code](https://github.com/lavacharts/issues/blob/master/223_cant-read-property-x-of-null/index.php), with a couple data points to test, and it rendered fine for me.

![image](https://user-images.githubusercontent.com/266076/30676703-46a63682-9e3c-11e7-9e6b-e15c8cb57749.png)

Can you post what `// add values to $chartname` is? or are you actually not adding any data initially, with the intent of loading after the fact?

**Comment by kevinkhill** [comment]
Closing due staleness and lack of communication. Please open a new issue of you still need assistance, as I am happy to help. ☺️
