### ISSUE TITLE
ReferenceError: lava is not defined

### ISSUE THREAD

**Issue by TheTechnoMan** [kevinkhill/lavacharts#226]
#### What Version?
3.1.8

#### Issue
```
ReferenceError: lava is not defined
```
The Lava.js file is not being included in the page (view). I don't quite see how I have to include it?
I upgraded from an older master version, before it worked without problems, so something ha sbeen changed since then.

Thanks

#### View Code
```

lava.ready(function() {
                $.getJSON(
                        $.getJSON('{{ route('get.graphs.fetch', 'registrations,loginAttempts') }}', function (dataTableJson) {
                            lava.loadData('registrations', dataTableJson.registrations, function (chart) {
                                $el_registrations.trigger('loading-overlay:hide');
                            });

                            lava.loadData('loginAttempts', dataTableJson.loginAttempts, function (chart) {
                                $el_loginAttempts.trigger('loading-overlay:hide');
                            });
                        }))
            });

@if(Lava::exists('AreaChart', 'registrations'))
            @areachart('registrations', 'registrations_div')
@endif
```

**Comment by kevinkhill** [comment]
The first call to a render method (in your case `@areachart`) will output both the lava.js module and the script block for rendering the chart. Subsequent render calls will only output chart code, since the `Lava` instance is tracking the output of the lava.js module.

The error is valid, since `lava.ready` is before the render call, and hence, lava doesn't exist yet.

What you can do, is add `Lava::lavajs()` before your `lava.ready()` code to force the output and placement of the `<script>` tag containing the lava.js module. Your ready call should then work and the `@areachart` call will not output the module again, since `Lava::` is tracking that it is already in page.

**Comment by TheTechnoMan** [comment]
Great, works like a charm! 

Thanks!

**Comment by kevinkhill** [comment]
No problem! Happy to help
