### ISSUE TITLE
How to create server side graph(i.e graph image)

### ISSUE THREAD

**Issue by Dinesh-Wasnik** [kevinkhill/lavacharts#234]
How to create graph image on server side.

**Comment by kevinkhill** [comment]
Since Google Charts is a front-end library, not easily. 

I've had success with PhantomJs & NightmareJs, but it takes some effort. 

You can [browse around the Javascript source](https://github.com/kevinkhill/lavacharts/tree/3.1/javascript) and see how I was able to do it. 

(I don't have time for detailed support, I'm sorry. Try playing around with it. It does work.)
