### ISSUE TITLE
Error publishing config

### ISSUE THREAD

**Issue by Ajay1432** [kevinkhill/lavacharts#235]
"php artisan vendor:publish --tag=lavacharts" not working

**Comment by kevinkhill** [comment]
Do you receive an error message? no console output? I need more to help you

**Comment by Ajay1432** [comment]
No nothing in console or as error message.
Just message "Publishing complete", But, nothing in confing folder.
I'm using Laravel 5.5

**Comment by kevinkhill** [comment]
I believe you were not getting the config to publish because you never registered the ServiceProvider.

I went ahead and merged in the auto-discovery config from the master branch to 3.1

You should be able to [update to 3.1.10](https://github.com/kevinkhill/lavacharts/releases/latest), the package will get discovered and registered, and then you can publish the config. :+1:

**Comment by Ajay1432** [comment]
It works after updating.
Thanks
