### ISSUE TITLE
Interface 'Carbon\CarbonInterface' not found 

### ISSUE THREAD

**Issue by sharmasourabh18** [kevinkhill/lavacharts#273]
#### What Version?
3.1
#### Issue
interface 'Carbon\CarbonInterface' not found 

#### Controller Code (chart creation code)
```
<?php

include('Carbon-master/src/Carbon/Carbon.php');
include('lavacharts-3.1/src/Lavacharts.php');

$lava = new \Khill\Lavacharts\Lavacharts;
$stocksTable = $lava->DataTable();  // Lava::DataTable() if using Laravel

$stocksTable->addDateColumn('Day of Month')
            ->addNumberColumn('Projected')
            ->addNumberColumn('Official');

// Random Data For Example
for ($a = 1; $a < 30; $a++) {
    $stocksTable->addRow([
      '2015-10-' . $a, rand(800,1000), rand(800,1000)
    ]);
}

echo $chart = $lava->LineChart('MyStocks', $stocksTable);
```

**Comment by kevinkhill** [comment]
It would appear that `Carbon` went through some major refactoring over the months I've been busy. `Lavacharts` is depending on `1.14` while the `Carbon` package is all the way up to `2.4.0` now :grimacing: 

Since the `Carbon` package is no longer self contained in a single file, you will have to manually include all if it's dependencies yourself if you choose to not use Composer.

Now that I know this is an issue, I hope to update and test the new version of `Carbon` and include it in my package. Even still, if you don't want to use Composer than that is still irrelevant.

**Comment by kevinkhill** [comment]
Closing due to staleness, please open a fresh issue if you are still having issues
