### ISSUE TITLE
Error with options

### ISSUE THREAD

**Issue by TheTechnoMan** [kevinkhill/lavacharts#35]
Hey, awesome package sadly I have a problem:

Argument 1 passed to Khill\Lavacharts\Charts\Chart::backgroundColor() must be an instance of Khill\Lavacharts\Configs\BackgroundColor, string given

My Code:
```
        $loginAttempts = LavachartsFacade::DataTable();

        $loginAttempts->addDateColumn('Date')
            ->addNumberColumn('Successful Attempts')
            ->addNumberColumn('Failed Attempts')
            ->addRow(array('2014-10-1', 67, 65))
            ->addRow(array('2014-10-2', 67, 18))
            ->addRow(array('2014-10-3', 0, 0))
            ->addRow(array('2014-10-4', 67, 65))
            ->addRow(array('2014-10-5', 67, 18))
            ->addRow(array('2014-10-6', 80, 64));

        $linechart = LavachartsFacade::LineChart('Temps')
            ->dataTable($loginAttempts)
            ->title('Login attempts within the last 7 days')
            ->setOptions(['backgroundColor' => 'red']);
```

Same error when I use ->backgroundColor

What am I doing wrong? I use Laravel 5.

Thanks

**Comment by kevinkhill** [comment]
Yes, because the backgroundColor method/option takes a BackgroundColor object, not a string.

[Chart, which is a parent to all charts](http://lavacharts.com/#charts) you can see the parameter is a [BackgroundColor](http://lavacharts.com#config-backgroundcolor) object.

In your case, you would do:
```
$bgColor = LavachartsFacade::BackgroundColor([
    'fill' => 'red'
])
```
and pass that object in
```
->setOptions(['backgroundColor' => $bgColor]);
```
The BackgroundColor object also has options for stroke (border) and strokeWidth (size in pixels)

Happy charting!

**Comment by TheTechnoMan** [comment]
Thanks, works fine! But when using stroke I get:

"stroke " is not a valid property for BackgroundColor->__construct, must be one of [ fill | stroke | strokeWidth ]

THat looks like a bug, right? :P

**Comment by kevinkhill** [comment]
Quite possibly, I'll look into it

**Comment by TheTechnoMan** [comment]
Thanks!

**Comment by TheTechnoMan** [comment]
Nevermind, my bad. Thewre is a space. Sorry

**Comment by kevinkhill** [comment]
It doesn't look like it, but that is a limitation on Google's behalf, not mine

[Line Chart config options](https://developers.google.com/chart/interactive/docs/gallery/linechart#Configuration_Options)

You could apply css border properties to the div that is containing the chart instead of having the border rendered via the chart?

**Comment by TheTechnoMan** [comment]
Alright, thanks!

**Comment by TheTechnoMan** [comment]
Okay, got one more question. Is there a way to show some sort of an loading image? I tried to place one directly into the div, sadly this resizes the div and therefore the chart is rendered in a small div. 

Thanks
