### ISSUE TITLE
Support for ScatterChart

### ISSUE THREAD

**Issue by singularity-xx** [kevinkhill/lavacharts#46]
Are there any plans for adding support for ScatterChart?  I've need for that and I've already found it easy to add new class and support for it. It's mostly compatible with columnChart but it has some own configuration options for points.  However I don't know your policy for accepting pull requests for new chart-types. 

If you not currently working on it, I could create new chart-class add support for at least to those point-specific options and add corresponding test-file. Do you think that's good way to proceed?

**Comment by kevinkhill** [comment]
You bring up some good points, and if you peek at the 3.0 branch, it is the first one I built with traits. I wanted making chart classes easy, so that's why I opted for inheritance plus traits, to quickly cover configuring new chart classes.

To answer your question, I would gladly accept pull requests for new charts. I only ask that you follow the style / configuration of the other chart classes.

You can probably copy the structure and point config objects from the 3.0 branch to get started if you want to contribute. :)

**Comment by singularity-xx** [comment]
Oh I see you already have everything in 3.0 branch. For some reason repository search didn't return anything for ScatterGraph so I didn't recognize that.  And configuration-objects are now shared between charts-classes using Traits. I got my code working with 3.0 when I passed dataTable as argument not through function-call.

I've no need to stay 2.5 so I'll just switch to this development version and notify if I encounter any problems. I really appreciate effort you have put to refactoring.
