### ISSUE TITLE
Can't we support all of Google Charts' options?

### ISSUE THREAD

**Issue by emilv** [kevinkhill/lavacharts#64]
I think Lavacharts should support any Google Charts option instead of just an arbitrary subset of them. For example, there seem to be no way to add `legend.maxLines`; neither as `maxLines` on the Legend object nor as pure `legend.maxLines` on the *Chart.

Now I just get this exception:

> "maxLines" is not a valid property for Legend->__construct, must be one of [ alignment | position | textStyle ] 

It feels like such an arbitrary limitation. I would love it if Lavacharts were just a small wrapper around the Google Charts API. What do you think?

**Comment by kevinkhill** [comment]
It was never intended to be a limitation. Originally, that probably wasn't an option, and Google added more options since the last time I went over those classes.

My intention was to type/error check the options, not handcuff the user. You do bring up a good point though.

**Comment by emilv** [comment]
Yeah, after sleeping on it I realized this must have been for type checking. Which in itself is way underestimated in PH circles and I do love that the exceptions are so clear. How do we strike a balance here, though? I can think of a few alternative solutions:

* Allow disabling type checking with an option or a boolean flag to the constructor
* Raising an old-type notification using trigger_error instead of throwing exceptions
* Just implement every damn option all the time they change the API, which I am certainly open to helping out with
* A specific function for setting "unknown" options

**Comment by kevinkhill** [comment]
Here's my thoughts on your thoughts:

 - I don't know if you have looked at the 3.0 branch at all, but the way options are set is a bit different than the 2.5 way. [Setting Options] (https://github.com/kevinkhill/lavacharts/wiki/Upgrading-from-2.5-to-3.0) This means there wouldn't be an easy way to have a constructor flag, since instansiation of the options objects takes place in the library, and not by the user.
- This seems like a good option. Thinking about it, setting a non existing option shouldn't cause a screeching halt, but at least let the user know they are setting something that doesn't exist.
- I would love to devote more time to developing Lavacharts, but I often work 50+ hour weeks at my day job. This, plus usual around the house stuff, leaves little time for working here. Although, I would graciously welcome any help and pull requests you are willing to contribute.
- This is another viable option... Maybe a generic setOption() method or something like that, but that comes back to v3.0, where the user isn't creating the options objects anymore.

**Comment by kevinkhill** [comment]
As a patch for this functionality, and to help you and others using the 2.5 branch (right?), I added a ```customize()``` method that will take an array and merge it into the other options. It should work for legend, like you requested, because the Legend object is converted with ```toArray()``` when added to the chart. I'm not sure if ```array_merge()``` will combine the two or just overwrite the legend object's array with a manual assignment of ```legend``` in the ```customize()``` method.

As a quick test I tried adding:
```
->customize([
    'explorer' => [
        'actions' => [
            'dragToPan',
            'rightClickToReset'
         ]
     ]
]);
```
to a LineChart and it works as expected.

I added this to the master branch, so if you would like to pull, test against it and report back... I would appreciate the help :)

I feel like this is a step in the right direction and will still work this into 3.1 as planned. Still need to finish the damn 3.0 docs first and release it.

**Comment by emilv** [comment]
This is a great middle ground! This has been a showstopper for us, and you pushed this fix at a time where we were just picking up a project that needs Google Charts. Just to be clear: it's only in the master branch yet?

**Comment by kevinkhill** [comment]
correct. I don't see any harm in bringing it into the 2.5 branch and tagging it if you don't want to depend on ```dev-master```

**Comment by emilv** [comment]
That's not an issue for us, you can release whenever you feel ready. I'll just use dev/master in my feature branch in the meantime.

**Comment by kevinkhill** [comment]
:+1: I will soon tag and add it for you and everyone else to enjoy

**Comment by emilv** [comment]
+1

This works great! Thank you!
