### ISSUE TITLE
Class 'App\Http\Controllers\Lava' not found

### ISSUE THREAD

**Issue by CharlesBilbo** [kevinkhill/lavacharts#91]
I've added "khill/lavacharts" : "2.5.*" to required in my composer.json file and than ran composer update after that i put "Khill\Lavacharts\Laravel\LavachartsServiceProvider"  in my config app file 
ive also tried back slashing Lava::MethodName and that doesnt seem to work either.

**Comment by kevinkhill** [comment]
Did you try the artisan dump also?

**Comment by CharlesBilbo** [comment]
yeah i have used artisan dump

**Comment by kevinkhill** [comment]
hmmm, are you sure the service provider line is added? In my dev environment, I deleted my symlink to lavacharts (I do this to not have to composer update all the time) and commented out the service provider line. Then I did a fresh composer pull of 2.5.9, and got the same error you stated, but I realized I had left it commented out, and upon removing the comments, my chart appeared.

**Comment by stevebauman** [comment]
Try using the full facade namespace? `Khill\Lavacharts\Laravel\LavachartsFacade`

Ex.

```php
use Khill\Lavacharts\Laravel\LavachartsFacade as Lava;
```

Or try pulling it out of the service container:

```php
$lava = app('lavacharts');
```

**Comment by kevinkhill** [comment]
:+1:

**Comment by kevinkhill** [comment]
I'm going to assume you figured this out, but if you didn't, please open a new issue and we'll keep working on this :)

**Comment by rargueso** [comment]
Same prob here! 

I think is cause Laravel namespace is undefined (Khill\Lavacharts\Laravel).

Using Laravel 5.2. 

Under Laravel 5.1 working fine.

**Comment by kevinkhill** [comment]
It's interesting to me that it worked by registering the service, and creating a Lava instance manually. The charts are stored within the Lava object. Did you pass your Lava object into the view?

**Comment by rargueso** [comment]
Yes. I did. Static call inside view didn't work.

Thanks for helping us! Your are doing a great job.

**Comment by kevinkhill** [comment]
I was curious, so I did a test for you. I am left confused as to why it won't work for you, because it works for me.

This is what I did:
1. Grabbed a fresh install of laravel ```composer create-project --prefer-dist laravel/laravel``` which installed ```5.2.*```
2. Added ```"khill/lavacharts":"3.0.*"```
3. ```composer update``` which installed Lavacharts ```3.0.1```
4. Added ```Khill\Lavacharts\Laravel\LavachartsServiceProvider::class``` to the providers array in ```config/app.php```
5. Created a simple line chart using ```\Lava::LineChart('test', $data)``` (no complaints about namespaces) in routes.php
6. Create a test blade view with ```<div id="line-div"></div>``` inside the body
7. Test rendered in a blade view with ```{!! \Lava::render('LineChart', 'test', 'line-div') !!}
8. Went back and moved the chart creation into a controller (again, no namespace complaints)
9. Tested again and the chart

**Comment by rargueso** [comment]
Thanks for testing.

I was wrong with Laravel version. It is 5.1.

```
php artisan --version
Laravel Framework version 5.1.30 (LTS)
```

My composer.json:
        "khill/lavacharts" : "3.0.*", (3.0.1 installed)

Added \Lava::LineChart('test', $data); to routes.php:

FatalErrorException in routes.php line 54:
Class 'Lava' not found

Same for controllers or views.

Im pretty sure that something is wrong with my project, because I have another one running fine with same version, I can't find what is it but ill update as soon as I know the reason.

**Comment by Kyiv85** [comment]
Hi Kevin!!, Thanks for the package!!,

Upgrading the package (And obviously the calls to the methods in controller and views), and especially adding the aliases works fine for me. I'm still using Laravel 5.0 and PHP 5.6.30. In this case:

'Lava' 		=> 'Khill\Lavacharts\Laravel\LavachartsFacade'

**Comment by Kyiv85** [comment]
Thanks a lot!!

**Comment by kevinkhill** [comment]
You are most welcome.
