### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by jowinkoh** [kevinkhill/lavacharts#93]
How to add animation for bar chart ? such as animation.startup, animation.easing and so on

**Comment by kevinkhill** [comment]
For the 2.5 branch, use an Animation object in the ```setOptions()``` method
```
$myChart->setOptions(array(
    'animation' => $lava->Animation(array(
        'easing' => 'linear'
   ))
))
```

For the 3.0 branch,  an Animation object in the ```setOptions()``` method
```
$myChart->setOptions(array(
    'animation' => $lava->Animation(array(
        'easing' => 'linear'
   ))
))
```

**Comment by jowinkoh** [comment]
i am using 2.5 branch. I have follow the code, but get this error message. ![image](https://cloud.githubusercontent.com/assets/15767914/12500494/aaa092ae-c0ee-11e5-9315-af804225dfd5.png)

**Comment by kevinkhill** [comment]
Hmm, it appears I must have missed adding that as an option for BarChart. You can use the ```customize()``` method to add any option you want, bypassing all checks.

I will probably not patch BarChart because 3.0 will be coming out soon, and I will eventually be removing the restrictions on what options are available. So there's no need to.

**Comment by jowinkoh** [comment]
Ok.Thanks

**Comment by kevinkhill** [comment]
I added the option for animation anyways, it was an easy fix. If you update with composer, you should get v2.5.10
